services:
  - type: web
    name: stokalite
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: info
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: RUN_MIGRATIONS
        value: "true"
